spring.application.name=dentalclinic
server.port=8080

#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/dental_clinic?useSSL=false&serverTimezone=UTC}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Manish@19}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://database-2.c4vkgs4ge8rz.us-east-1.rds.amazonaws.com:3306/dental_clinic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mypassword9835787154}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#mysql -h database-2.c4vkgs4ge8rz.us-east-1.rds.amazonaws.com -P 3306 -u admin -p

# Email (SMTP)
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:mk8516054@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:tymrdnigmblwysqk}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS:true}
app.contact.recipient-email=${APP_CONTACT_RECIPIENT_EMAIL:${SPRING_MAIL_USERNAME:mk8516054@gmail.com}}


# JWT settings (use a strong secret in production)
app.jwt.secret=${APP_JWT_SECRET:change-me-super-secret-key-change-me-super-secret-key}
app.jwt.expiration-ms=86400000

# Razorpay
#app.razorpay.key-id=${APP_RAZORPAY_KEY_ID:rzp_test_Sd8vXR0Fqmh1i0}
#app.razorpay.key-secret=${APP_RAZORPAY_KEY_SECRET:l3b0ON5IK1RcfmM3JpBdMzRO}
app.razorpay.key-id=${APP_RAZORPAY_KEY_ID:rzp_live_SiT13U5s5BI9wr}
app.razorpay.key-secret=${APP_RAZORPAY_KEY_SECRET:q4ZPwPpEHO1oRNZPWGhiMvj8}
app.razorpay.currency=${APP_RAZORPAY_CURRENCY:INR}
app.razorpay.webhook-secret=${APP_RAZORPAY_WEBHOOK_SECRET:}

# File uploads
app.upload-dir=${APP_UPLOAD_DIR:uploads}

# Admin bootstrap (dev)
app.admin.email=${APP_ADMIN_EMAIL:admin@gmail.com}
app.admin.password=${APP_ADMIN_PASSWORD:root}

# Respect X-Forwarded-* headers when running behind SSL-terminating proxy/load balancer
server.forward-headers-strategy=${SERVER_FORWARD_HEADERS_STRATEGY:framework}

# Comma-separated CORS origin allow-list
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://gayatridental.com,https://www.gayatridental.com,http://localhost:*,http://127.0.0.1:*,http://localhost:5173,http://localhost:3000}
